### ISSUE TITLE
Nielsen-Thurston Classification in Walkthrough Fails

### ISSUE THREAD

**Issue by FayeAlephNil** [MarkCBell/curver#14]
**Describe the bug**
Nielsen-Thurston Classification on simple mapping classes from the walkthrough fails with an error

**To Reproduce**
Steps to reproduce the behavior: Start python and run the following code
```python
import curver
S = curver.load(1,2)
h = S('a_0.b_0')
h.nielsen_thurston_type()
```

**Expected behavior**
An identification that this is a reducible mapping class, since h(a) = a for a = S.arcs['s_1']. 

**Screenshots**
![image](https://github.com/user-attachments/assets/1ab369f4-bef2-45e2-ae22-954d5fd6702b)

** Error Log**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/faye/Documents/Research/LefschetzJupyter/.venv/lib/python3.12/site-packages/curver/kernel/encoding.py", line 333, in nielsen_thurston_type
    elif self.is_reducible():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/faye/Documents/Research/LefschetzJupyter/.venv/lib/python3.12/site-packages/curver/kernel/encoding.py", line 318, in is_reducible
    if C.distance(c, self(c, power=k)) < D:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/faye/Documents/Research/LefschetzJupyter/.venv/lib/python3.12/site-packages/curver/kernel/curvegraph.py", line 158, in distance
    return len(self.geodesic(a, b)) - 1
               ^^^^^^^^^^^^^^^^^^^
  File "/home/faye/Documents/Research/LefschetzJupyter/.venv/lib/python3.12/site-packages/curver/kernel/curvegraph.py", line 147, in geodesic
    assert isinstance(a, curver.kernel.Curve)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Curver 0.4.1

**Comment by MarkCBell** [comment]
Thanks for this report. Can you reproduce this in curver v0.5.0?

**Comment by FayeAlephNil** [comment]
Yes I just reproduced this in curver v0.5.0. It seems the issue is that the curves being created by `is_reducible()` are treated as `MultiCurve`s rather than `Curve`s, and `geodesic(a,b)` isn't able to handle this type :)

**Comment by MarkCBell** [comment]
Thanks for flagging this. I've released v0.5.1 which I think fixes this. Could you try this out? Note that if you are interested in actually determining the NT type of interesting mapping classes then flipper is more likely to be able to do this for you for real examples.
